# pyproject.toml
[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "setuptools_scm>=6.2",
    "setuptools_scm_git_archive>=1.0",
    ]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "firemon_api/version.py"